### ISSUE TITLE
How can I navigate another page with connect that navbar?

### ISSUE THREAD

**Issue by farhansadikgalib** [haptome/dot_navigation_bar#2]
How to connect nav bar with page.?

**Comment by haptome** [comment]
hello there, if you just follow this code you might find out.


     class Run extends StatefulWidget {
      @override
      _RunState createState() => _RunState();
    }

    class _RunState extends State<Run> with WidgetsBindingObserver {
      int _currentIndex;

      @override
      void initState() {
        super.initState();

    _currentIndex = widget.index;
      }

      void changePage(int index) {
        setState(() {
      _currentIndex = index;
        });
      }

      final tabs = [
        Home(),
        ListProduct(),
        OrdersPage(),
        SetUP(),
        ProfilePage(),
      ];

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          backgroundColor: Color(0xFFf3f6fb),
          // extendBody: true,
          body: tabs[_currentIndex],
          bottomNavigationBar: BottomNavigationBar(
            type: BottomNavigationBarType.fixed,
            showSelectedLabels: true,
            showUnselectedLabels: true,
            onTap: changePage, // new
            currentIndex: _currentIndex, // new
            selectedItemColor: ColorConstant.shemsuTextBodyColor,
            unselectedItemColor: Colors.grey[400],
            items: [
              // BottomNavigationBarItem(),
              // BottomNavigationBarItem(),
              // BottomNavigationBarItem(),
              //BottomNavigationBarItem(),
            ],
          ),
        );
      }
    }

**Comment by kyleorin** [comment]
is there any way I could make a DotNavigationBarItem navigate to a whole new screen (without showing the bottomnavbar)
