### ISSUE TITLE
RangeError (index): Invalid value: Not in inclusive range 0..3: 4

### ISSUE THREAD

**Issue by orcecso** [haptome/dot_navigation_bar#3]
Hello,

I am trying to use the DotNavigationbar plugin in flutter, 

all is working but since i added a 5th item or basically a 4th index, it shows the error at the top
(RangeError (index): Invalid value: Not in inclusive range 0..3: 4)

This is the Screenshot of the item i added, working with 4 items only is okay, but i needed a 5th one,

![image](https://user-images.githubusercontent.com/58863067/127773299-8a8ecc70-e8f6-48bf-942e-9bff0cd9ed72.png)

Thanks

**Comment by haptome** [comment]
hello there,
after you adding the 5th item hot reload did't help just restart you project again and the error will be gone.
