### ISSUE TITLE
Disable Splash Color

### ISSUE THREAD

**Issue by luis-cruzt** [haptome/dot_navigation_bar#5]
Is there a way to disable the splash color when an item is tapped?

**Comment by luis-cruzt** [comment]
Thanks

**Comment by srcho** [comment]
I'm waiting, too. It's the ripple effect when you press the navigation bar, right?

**Comment by pzehle** [comment]
Would be nice if this is updated in the pub registry. I am new to PR's, but is there any way I can help with that?
